language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qtbase5-dev
            - qttools5-dev
            - liblua5.2-dev
            - libcairo2-dev
            - liblog4cxx10-dev
            - libpango1.0-dev
            - libboost-all-dev
            - libqt5svg5-dev
            - libgtest-dev
            - libeigen3-dev
            - libcurl4-gnutls-dev
            - libgtk-3-dev
            - libgdk-pixbuf2.0-dev
            - gcc-4.9
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

cache: ccache

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p third_party
  - cd third_party
  - mkdir -p gtest_build
  - cd gtest_build
  - cmake /usr/src/gtest
  - make -j2
  - cd ..
  - git clone https://github.com/rvt/libdxfrw.git libdxfrw
  - cd libdxfrw
  - cmake .
  - make -j2
  - cd ../..
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j2
  - ./unittest/lcunittest

notifications:
  irc:
    channels:
      - "chat.freenode.net#librecad"
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Result: %{result} in %{duration}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"